services:
  mongodb:
    image: mongo:7.0
    container_name: blog-mongodb

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: blog_mern
    
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/config


    ports: 
      - "27017:27017"


volumes:
  mongodb_data:
  mongodb_config:



